Flight_Planner_done
NikitaKrivec/Flight-Planner pull request #1
Opened 2022-09-28 14:15 UTC by NikitaKrivec

Flight_planner done

2022-09-30 07:17 UTC, EdgarsSalmins commented on FlightPlanner/FlightPlanner/Controllers/WeatherForecastController.cs
> +    public class WeatherForecastController : ControllerBase
jāmet ārā.

2022-09-30 07:19 UTC, EdgarsSalmins commented on FlightPlanner/FlightPlanner/WeatherForecast.cs
> +    public class WeatherForecast
jāmet ārā.

2022-09-30 07:20 UTC, EdgarsSalmins requested changes
bin, obj mapes jāmet ārā. :) + weather forecast lietas jāizmet. :) pārējais fine.

2022-09-30 10:47 UTC, NikitaKrivec commented on FlightPlanner/FlightPlanner/WeatherForecast.cs
> +    public class WeatherForecast
Fixed

2022-09-30 10:47 UTC, NikitaKrivec commented on FlightPlanner/FlightPlanner/Controllers/WeatherForecastController.cs
> +    public class WeatherForecastController : ControllerBase
Fixed

2022-10-03 17:09 UTC, EdgarsSalmins approved these changes

2022-10-03 17:09 UTC, merged